### ISSUE TITLE
About # of transformerdecoder layers

### ISSUE THREAD

**Issue by samsara-ku** [theEricMa/DiffSpeaker#10]
Is it okay to set just `num_layers` as 1 for `TransformerDecoderLayer_w_Adapter` class when training your model?

Some other models just use their `num_layers` as 6 or 8, is this just a simple curiosity.

**Comment by theEricMa** [comment]
We follow the configuration in [FaceFormer](https://github.com/EvelynFan/FaceFormer/blob/dfaea81983665b22b99af336a80574208cfcc099/faceformer.py#L82), which uses just one layer of Transformer. You can add more layers, which can improve performance.
