### ISSUE TITLE
[Ask] Extract FLAME expression parameter from predicted vertex

### ISSUE THREAD

**Issue by yjhong89** [theEricMa/DiffSpeaker#13]
Hi! Thanks for sharing great works!

- DiffSpeaker diffusion model outputs vertex corresponding to audio at timestep `t`.
- Then is there any way extract expression and other FLAME parameters from predicted FLAME vertex ??

Thanks!

**Comment by theEricMa** [comment]
Hi. To obtain FLAME parameters from audio, you have two options:

1. If you have a dataset that includes both audio and synchronized FLAME parameter sequences, you can train a DiffSpeaker model using your own data.
2. If you want to convert generated FLAME vertices into their corresponding coefficients using existing models, you'll need to perform coefficient regression. This involves finding FLAME parameters that result in the smallest distance from the provided FLAME vertices. Then you need to write some code to optimize this distance.

**Comment by yjhong89** [comment]
Thanks for your answer.
- For number 1. 
  - If I have audio-synchronized FLAME parameters, then diffusion model would predict FLAME parameter sequence rather than vertex offset ?

**Comment by theEricMa** [comment]
Yes, it can. You can train a new model to do so. The main difference is that it predicts several tens of coefficients instead of several thousand.

**Comment by yjhong89** [comment]
Thanks!

**Comment by myw8** [comment]
> Yes, it can. You can train a new model to do so. The main difference is that it predicts several tens of coefficients instead of several thousand.

I used FLAME parameter to train a new model, but the prediction performance is poor. What should I do and how should I modify it

**Comment by theEricMa** [comment]
Hi, @myw8. You can adjust the network architecture by adding more layers in the [config file](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/vocaset/diffspeaker_wav2vec2_vocaset.yaml#L56). By the way, which dataset are you working with?

**Comment by myw8** [comment]
> Hi, @myw8. You can adjust the network architecture by adding more layers in the [config file](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/vocaset/diffspeaker_wav2vec2_vocaset.yaml#L56). By the way, which dataset are you working with?

I used about 100 hours of data collected by ourselves, set 5 layers  in the config to predict spectre exp. During training, the convergence of the loss was very slow, and after one week of training, the loss remained at 0.007 and did not decrease. The performance of the prediction demo was still relatively poor.

**Comment by theEricMa** [comment]
Could you please tell me the FPS of your generated frames? In Vocaset, it is [30 FPS](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/vocaset/diffspeaker_wav2vec2_vocaset.yaml#L70), and in BIWI, it is [25 FPS](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/biwi/diffspeaker_wav2vec2_biwi.yaml#L70). Setting the correct FPS is important.
