### ISSUE TITLE
inference problem

### ISSUE THREAD

**Issue by yangan200203** [theEricMa/DiffSpeaker#16]
作者您好，我按照您给的推断过程得到的biwi数据的metric很奇怪，我不知道哪里出现了问题。得到的结果错的很离谱
![i讯飞图片_1721738345363](https://github.com/user-attachments/assets/7880df5a-c447-4106-befd-3586f1a7e9bc)

**Comment by yangan200203** [comment]
是hubert版本的

**Comment by yangan200203** [comment]
请问hubert-base-ls960版本的processor使用的还是wav2vec2.0的processor吗

**Comment by theEricMa** [comment]
<img width="849" alt="image" src="https://github.com/user-attachments/assets/87a96ad7-991b-415d-a5cd-b963593b4dc4">

你好，我们使用 [hubert](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/biwi/diffspeaker_hubert_biwi.yaml#L46) 和 [wav2vec 2.0](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/configs/diffusion/biwi/diffspeaker_wav2vec2_biwi.yaml#L46) 时采用的是相同的代码，仅仅是 load 的 backbone 不同。在我的机器上hubert 跑 biwi 的实验结果如下，和论文里的一致。想问一下：


1. 使用 Wav2vec 2.0 作为 backbone 会不会也出现 metric 不准确的问题
2. [diffuser](https://github.com/theEricMa/DiffSpeaker/blob/0f2ae2d4e88fe78bff8bb7a1fdbc628e8733f120/requirements.txt#L17) 的版本是不是0.11

**Comment by yangan200203** [comment]
确实是diffusers版本的问题，我修改之后就正常了，感谢您的回复。

**Comment by yangyifan18** [comment]
> 确实是diffusers版本的问题，我修改之后就正常了，感谢您的回复。

您好，可以分享一下biwi数据集吗，官方链接失效了，我也联系不上作者，感谢！

**Comment by theEricMa** [comment]
我把 biwi 上传到了[Google Drive](https://drive.google.com/file/d/1H14hou1Gz5F7oqqb_g5-Vw2g8ECPMoHH/view?usp=sharing). 解压后放在`./datasets`目录下即可
