### ISSUE TITLE
About calculating LVE on VOCASET

### ISSUE THREAD

**Issue by chacorp** [theEricMa/DiffSpeaker#7]
Hi! thanks for the great work

I have a question about calculating LVE on VOCASET.
How did you select the lip vertices? Did you define it manually or is there a reference?

Thanks in advance!

**Comment by theEricMa** [comment]
Thanks for your interest in our work!. It is provided by [SelfTalk](https://github.com/psyai-net/SelfTalk_release/blob/main/vocaset/FLAME_masks.pkl).
