### ISSUE TITLE
Testing on a different template?

### ISSUE THREAD

**Issue by therealron** [theEricMa/DiffSpeaker#9]
Hi, wonderful work! Thanks for sharing. I am trying to run inference on the model trained on Vocaset, but on a different template and am getting wrong results. All I did was change the template that was being used. my template is of the same topology as flame so I was expecting to see something reasonable at least even though its not in the training set. Can you share how I can fix this? Thanks! :)
<img width="661" alt="image" src="https://github.com/theEricMa/DiffSpeaker/assets/41287218/7689b262-e49f-4f67-bc08-1548343484bb">

**Comment by therealron** [comment]
<img width="643" alt="image" src="https://github.com/theEricMa/DiffSpeaker/assets/41287218/d73a03d3-3d7a-46cd-adb4-e441172de1da">

This is what my template looks like.

**Comment by therealron** [comment]
Sorry I was able to solve it. I was using trimesh to read the mesh which seems to reorder the vertices for some reason. If i use igl to read the mesh I'm getting the right results. 
![image](https://github.com/theEricMa/DiffSpeaker/assets/41287218/aaf629c2-0f00-4d9c-bc77-9d5a3492bf0c)

**Comment by theEricMa** [comment]
Thanks for the info!
